spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create
  eureka:
    instance:
      # enable to register multiple app instances with a random server port
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}